### ISSUE TITLE
Parsing of cron expression with both range and individual hour fails

### ISSUE THREAD

**Issue by hansjorg** [Salamek/cron-descriptor#14]
Possibly same issue as #6, but with hours rather than days.

```python
>>> from cron_descriptor import get_description, ExpressionDescriptor
>>> print(get_description("15 6,10-20 * * *"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cron-descriptor-test/env/local/lib/python2.7/site-packages/cron_descriptor/ExpressionDescriptor.py", line 582, in get_description
    return descripter.get_description(DescriptionTypeEnum.FULL)
  File "cron-descriptor-test/env/local/lib/python2.7/site-packages/cron_descriptor/ExpressionDescriptor.py", line 101, in get_description
    description = choices.get(description_type, self.get_seconds_description)()
  File "cron-descriptor-test/env/local/lib/python2.7/site-packages/cron_descriptor/ExpressionDescriptor.py", line 149, in get_full_description
```

**Comment by Salamek** [comment]
@hansjorg fixed in 1.2.9 and PIP updated
