### ISSUE TITLE
Fails to parse crontab with full day of week name

### ISSUE THREAD

**Issue by nijel** [Salamek/cron-descriptor#65]
Originally reported at https://github.com/celery/django-celery-beat/issues/647

Having crontab `0 2 * * monday` leads to an exception (`FormatException: null`):

```pytb
Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 131, in get_full_description
    day_of_week_desc = self.get_day_of_week_description()
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 342, in get_day_of_week_description
    return self.get_segment_description(
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 467, in get_segment_description
    description = get_description_format(expression).format(get_single_item_description(expression))
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 345, in <lambda>
    lambda s: get_day_name(s),
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 315, in get_day_name
    return ExpressionDescriptor.number_to_day(int(exp))

During handling of the above exception (invalid literal for int() with base 10: '1DAY'), another exception occurred:
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 85, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1894, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django_celery_beat/admin.py", line 155, in changeform_view
    crontab_dict[crontab.id] = crontab.human_readable
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/django_celery_beat/models.py", line 319, in human_readable
    human_readable = get_description('{} {} {} {} {}'.format(
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 664, in get_description
    return descripter.get_description(DescriptionTypeEnum.FULL)
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 108, in get_description
    description = choices.get(description_type, self.get_seconds_description)()
  File "/home/weblate/weblate-env/lib/python3.9/site-packages/cron_descriptor/ExpressionDescriptor.py", line 148, in get_full_description
    raise FormatException(description)
```

The following code handles `mon` fine, but turns `monday` into `1DAY`:

https://github.com/Salamek/cron-descriptor/blob/0c575c6b9ca13ac8e004237cb9e6ba81f7f544d3/cron_descriptor/ExpressionParser.py#L172-L174

That later fails in conversion to int. The conversion in celery works the other way – it extracts the first three letters of the string and uses that to convert to the int:

https://github.com/celery/celery/blob/3ce5b85806104e14f75a377fadc4de3e50038396/celery/utils/time.py#L215-L227

**Comment by Salamek** [comment]
Umm since when is full day name allowed in CRON expression?

**Comment by Salamek** [comment]
Python-crontab is also using 3 char day names in it's docs...
https://pypi.org/project/python-crontab/

**Comment by nijel** [comment]
Celery supports that (see referenced code). It might not be standard, though...

**Comment by Salamek** [comment]
@nijel how i now wrote in previous comment, it is issue of `celery.schedules.crontab` and when it builds crontab string it passes incorrect value there...

**Comment by nijel** [comment]
Yes, it might do a better job. But the way cron-descriptor crashed is not really helpful. I would not mind if it reported invalid input, but instead there is none exception message and the intermediate one contains something about 1DAY what has really nothing to do with the original string.

**Comment by Salamek** [comment]
Hehe, this is not cron expression validator for sure... :-) Also that `1DAY` is result of 'monday '.upper().replace('MON', '1')  on line https://github.com/Salamek/cron-descriptor/blob/0c575c6b9ca13ac8e004237cb9e6ba81f7f544d3/cron_descriptor/ExpressionParser.py#L174

But i'll consider adding some kind of validation / better parsing exceptions...

**Comment by Salamek** [comment]
(Should be) Fixed in downstream...
